export {
	type ContextUsage,
	createExtensionRuntime,
	discoverAndLoadExtensions,
	type Extension,
	type ExtensionCommandContextActions,
	type ExtensionErrorListener,
	type ExtensionFactory,
	ExtensionRunner,
	type ExtensionRuntime,
	type ExtensionUIContext,
	emitSessionShutdownEvent,
	type InputSource,
	type LoadExtensionsResult,
	loadExtensionFromFactory,
	loadExtensions,
	type MessageEndEvent,
	type MessageStartEvent,
	type MessageUpdateEvent,
	type ReplacedSessionContext,
	type SessionBeforeCompactResult,
	type SessionBeforeTreeResult,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type ShutdownHandler,
	type SlashCommandInfo,
	type SlashCommandSource,
	type SourceInfo,
	type ToolDefinition,
	type ToolExecutionEndEvent,
	type ToolExecutionStartEvent,
	type ToolExecutionUpdateEvent,
	type ToolInfo,
	type TreePreparation,
	type TurnEndEvent,
	type TurnStartEvent,
	wrapRegisteredTools,
} from "../../coding-agent/src/core/extensions/index.js";
