import type {
	ArtifactOutputRequirement,
	JsonObject,
	TypedArtifactPayload,
	WorkerRequest,
} from "@mariozechner/pi-agent-contracts";
import { type ArtifactRef, createExecutionTrace, type WorkerResult } from "@mariozechner/pi-agent-contracts";
import {
	type ArtifactStore,
	artifactToRef,
	createTypedArtifactWriter,
	type StoredArtifact,
} from "@mariozechner/pi-artifact-core";
import type { LeadAgentWorkerRunner } from "../orchestration/types.js";

export interface CreateStructuredProfileRunnerOptions {
	store: ArtifactStore;
}

const PLACEHOLDER_RUNNER_MARKERS = {
	runnerMode: "placeholder-structured-runner",
	modelBacked: false,
	verificationRequired: true,
} as const satisfies JsonObject;

const PLACEHOLDER_SUMMARY =
	"Generated placeholder structured output for plumbing validation; model-backed profile execution is not implemented.";

function artifactRequirements(request: WorkerRequest): ArtifactOutputRequirement[] {
	return (
		request.outputContract?.requirements.filter(
			(requirement): requirement is ArtifactOutputRequirement => requirement.kind === "artifact",
		) ?? []
	);
}

function sourceArtifactIds(request: WorkerRequest): string[] {
	return request.inputArtifacts.map((artifact) => artifact.id);
}

function markTypedPayload<T extends TypedArtifactPayload>(payload: T): T & typeof PLACEHOLDER_RUNNER_MARKERS {
	return {
		...payload,
		...PLACEHOLDER_RUNNER_MARKERS,
	};
}

function typedPayloadFor(
	kind: TypedArtifactPayload["kind"],
	request: WorkerRequest,
): TypedArtifactPayload & typeof PLACEHOLDER_RUNNER_MARKERS {
	if (kind === "evidence-table") {
		return markTypedPayload({
			kind: "evidence-table",
			rows: [
				{
					claimId: `${request.taskId}:claim-1`,
					claim: request.objective,
					support: "uncertain",
					sourceArtifactIds: sourceArtifactIds(request),
					notes: "Deterministic structured runner placeholder pending model-backed generation.",
				},
			],
			uncertaintySummary: "Generated by deterministic structured runner; verify before citation use.",
		});
	}
	if (kind === "claim-audit") {
		return markTypedPayload({
			kind: "claim-audit",
			entries: [
				{
					claimId: `${request.taskId}:claim-1`,
					claim: request.objective,
					status: "missing-citation",
					sourceArtifactIds: sourceArtifactIds(request),
					rationale: "Deterministic structured runner placeholder pending model-backed claim audit.",
				},
			],
			unsupportedCount: 1,
		});
	}
	return markTypedPayload({
		kind: "bibliography-candidates",
		queryPlan: [request.objective],
		candidates: [],
		retrievalGaps: ["No provider-backed retrieval was run by the structured profile runner."],
	});
}

function genericPayloadFor(kind: string, request: WorkerRequest): JsonObject {
	return {
		...PLACEHOLDER_RUNNER_MARKERS,
		kind,
		objective: request.objective,
		expectedOutputs: request.expectedOutputs,
		sourceArtifactIds: sourceArtifactIds(request),
		note: "Deterministic structured runner placeholder pending model-backed generation.",
	};
}

function writeArtifactForRequirement(
	store: ArtifactStore,
	request: WorkerRequest,
	requirement: ArtifactOutputRequirement,
): StoredArtifact {
	if (
		requirement.artifactKind === "evidence-table" ||
		requirement.artifactKind === "claim-audit" ||
		requirement.artifactKind === "bibliography-candidates"
	) {
		return createTypedArtifactWriter(store).write({
			kind: requirement.artifactKind,
			title: requirement.label,
			payload: typedPayloadFor(requirement.artifactKind, request),
			lineage: sourceArtifactIds(request),
			metadata: {
				...PLACEHOLDER_RUNNER_MARKERS,
				contractId: request.outputContract?.contractId ?? "",
				requirementId: requirement.id,
			},
		});
	}
	return store.create({
		kind: requirement.artifactKind,
		title: requirement.label,
		mediaType: "application/json",
		content: `${JSON.stringify(genericPayloadFor(requirement.artifactKind, request), null, 2)}\n`,
		lineage: sourceArtifactIds(request),
		metadata: {
			...PLACEHOLDER_RUNNER_MARKERS,
			contractId: request.outputContract?.contractId ?? "",
			requirementId: requirement.id,
		},
	});
}

function artifactBriefsFor(artifacts: readonly ArtifactRef[]): WorkerResult["artifactBriefs"] {
	return artifacts.map((artifact) => ({
		artifactId: artifact.id,
		kind: artifact.kind,
		title: artifact.title,
		brief: `Structured profile runner produced ${artifact.kind}.`,
	}));
}

export function createStructuredProfileRunner(options: CreateStructuredProfileRunnerOptions): LeadAgentWorkerRunner {
	return async (request) => {
		const storedArtifacts = artifactRequirements(request).map((requirement) =>
			writeArtifactForRequirement(options.store, request, requirement),
		);
		const producedArtifacts = storedArtifacts.map(artifactToRef);
		return {
			taskId: request.taskId,
			status: "success",
			summary: PLACEHOLDER_SUMMARY,
			structuredOutputs: {
				...PLACEHOLDER_RUNNER_MARKERS,
				expectedOutputs: request.expectedOutputs,
				artifactKinds: producedArtifacts.map((artifact) => artifact.kind),
			},
			producedArtifacts,
			artifactBriefs: artifactBriefsFor(producedArtifacts),
			warnings: [],
			openQuestions: [],
			executionTrace: createExecutionTrace(`structured-profile-${request.taskId}`),
		};
	};
}
